[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["Nathan Bird <nathanbirdka@gmail.com>"]
description = "Sample project using wasm-pack in rust"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.92"